# Generated by Django 4.2.30 on 2026-06-30 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('project_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('value_thb', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_phase', models.CharField(choices=[('pre_sale', 'Pre-sale'), ('execution', 'Execution'), ('ma', 'MA'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='pre_sale', max_length=12)),
                ('health_status', models.CharField(choices=[('not_started', 'ยังไม่เริ่ม'), ('on_plan', 'ตามแผน'), ('at_risk', 'เสี่ยง'), ('delay', 'ล่าช้า'), ('completed', 'เสร็จสมบูรณ์')], default='not_started', max_length=12)),
                ('health_reason', models.CharField(blank=True, max_length=255)),
                ('delay_days', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client')),
                ('po_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(blank=True, max_length=128)),
                ('responsibilities', models.TextField(blank=True)),
                ('allocation_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
