# Generated by Django 4.2.30 on 2026-06-30 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('get_req', 'Get Req'), ('design', 'Design'), ('development', 'Development'), ('test', 'Test'), ('training', 'Training'), ('go_live', 'Go Live')], default='get_req', max_length=12)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('working', 'Working'), ('stuck', 'Stuck'), ('done', 'Done'), ('verified', 'Verified')], default='not_started', max_length=12)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('meeting', 'Meeting'), ('plan', 'Plan')], default='manual', max_length=8)),
                ('estimated_manday', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('unclaim_reason', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('plan_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='plans.planitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
