# Generated by Django 4.2.30 on 2026-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('meeting', 'Meeting'), ('plan', 'Plan'), ('external', 'External')], default='manual', max_length=8),
        ),
    ]
