# Generated by Django 4.2.30 on 2026-07-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
