# Generated by Django 4.2.30 on 2026-06-30 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('meeting', 'Meeting'), ('plan', 'Plan')], default='manual', max_length=8)),
                ('title', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('is_general', models.BooleanField(default=True)),
                ('status_snapshot', models.CharField(blank=True, max_length=12, null=True)),
                ('hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('is_ot', models.BooleanField(default=False)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entries', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'work_date'], name='daily_daily_user_id_bd4708_idx')],
            },
        ),
    ]
