# Generated by Django 4.2.30 on 2026-07-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='is_general',
        ),
    ]
