# Generated by Django 4.2.30 on 2026-07-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_worksummarynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksummarynote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='worksummarynote',
            unique_together=set(),
        ),
    ]
