# Generated by Django 4.2.30 on 2026-06-30 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('manpower', 'Manpower / LOE'), ('infra', 'Server / Infrastructure'), ('subscription', 'Subscription / Tools'), ('system', 'System / Custom'), ('custom', 'Custom')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('qty_or_units', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('months', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_override', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('is_outsource', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
