# Generated by Django 4.2.30 on 2026-07-04 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_risk_risklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('server', 'Server'), ('subscription', 'Subscription'), ('domain', 'Domain'), ('license', 'License'), ('other', 'อื่นๆ')], default='server', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(blank=True, choices=[('dev', 'Dev'), ('uat', 'UAT'), ('prod', 'Production')], max_length=8)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('billing_cycle', models.CharField(choices=[('one_time', 'จ่ายครั้งเดียว'), ('monthly', 'รายเดือน'), ('yearly', 'รายปี')], default='monthly', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'ใช้งานอยู่'), ('cancelled', 'ยกเลิกแล้ว')], default='active', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infra_assets', to='projects.project')),
            ],
            options={
                'ordering': ['expires_at', '-created_at'],
            },
        ),
    ]
